NAME: node-feature-discovery-1711027422
LAST DEPLOYED: Thu Mar 21 13:23:42 2024
NAMESPACE: node-feature-discovery
STATUS: pending-install
REVISION: 1
TEST SUITE: None
HOOKS:
MANIFEST:
---
# Source: node-feature-discovery/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-feature-discovery-1711027422
  namespace: node-feature-discovery
  labels:
    helm.sh/chart: node-feature-discovery-0.15.3
    app.kubernetes.io/name: node-feature-discovery
    app.kubernetes.io/instance: node-feature-discovery-1711027422
    app.kubernetes.io/version: "v0.15.3"
    app.kubernetes.io/managed-by: Helm
---
# Source: node-feature-discovery/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-feature-discovery-1711027422-gc
  namespace: node-feature-discovery
  labels:
    helm.sh/chart: node-feature-discovery-0.15.3
    app.kubernetes.io/name: node-feature-discovery
    app.kubernetes.io/instance: node-feature-discovery-1711027422
    app.kubernetes.io/version: "v0.15.3"
    app.kubernetes.io/managed-by: Helm
---
# Source: node-feature-discovery/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-feature-discovery-1711027422-worker
  namespace: node-feature-discovery
  labels:
    helm.sh/chart: node-feature-discovery-0.15.3
    app.kubernetes.io/name: node-feature-discovery
    app.kubernetes.io/instance: node-feature-discovery-1711027422
    app.kubernetes.io/version: "v0.15.3"
    app.kubernetes.io/managed-by: Helm
---
# Source: node-feature-discovery/templates/nfd-master-conf.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-feature-discovery-1711027422-master-conf
  namespace: node-feature-discovery
  labels:
    helm.sh/chart: node-feature-discovery-0.15.3
    app.kubernetes.io/name: node-feature-discovery
    app.kubernetes.io/instance: node-feature-discovery-1711027422
    app.kubernetes.io/version: "v0.15.3"
    app.kubernetes.io/managed-by: Helm
data:
  nfd-master.conf: |-
    null
---
# Source: node-feature-discovery/templates/nfd-topologyupdater-conf.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-feature-discovery-1711027422-topology-updater-conf
  namespace: node-feature-discovery
  labels:
    helm.sh/chart: node-feature-discovery-0.15.3
    app.kubernetes.io/name: node-feature-discovery
    app.kubernetes.io/instance: node-feature-discovery-1711027422
    app.kubernetes.io/version: "v0.15.3"
    app.kubernetes.io/managed-by: Helm
data:
  nfd-topology-updater.conf: |-
    null
---
# Source: node-feature-discovery/templates/nfd-worker-conf.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-feature-discovery-1711027422-worker-conf
  namespace: node-feature-discovery
  labels:
    helm.sh/chart: node-feature-discovery-0.15.3
    app.kubernetes.io/name: node-feature-discovery
    app.kubernetes.io/instance: node-feature-discovery-1711027422
    app.kubernetes.io/version: "v0.15.3"
    app.kubernetes.io/managed-by: Helm
data:
  nfd-worker.conf: |-
    null
---
# Source: node-feature-discovery/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-feature-discovery-1711027422
  labels:
    helm.sh/chart: node-feature-discovery-0.15.3
    app.kubernetes.io/name: node-feature-discovery
    app.kubernetes.io/instance: node-feature-discovery-1711027422
    app.kubernetes.io/version: "v0.15.3"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/status
  verbs:
  - get
  - patch
  - update
  - list
- apiGroups:
  - nfd.k8s-sigs.io
  resources:
  - nodefeatures
  - nodefeaturerules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  resourceNames:
  - "nfd-master.nfd.kubernetes.io"
  verbs:
  - get
  - update
---
# Source: node-feature-discovery/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-feature-discovery-1711027422-gc
  labels:
    helm.sh/chart: node-feature-discovery-0.15.3
    app.kubernetes.io/name: node-feature-discovery
    app.kubernetes.io/instance: node-feature-discovery-1711027422
    app.kubernetes.io/version: "v0.15.3"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/proxy
  verbs:
  - get
- apiGroups:
  - topology.node.k8s.io
  resources:
  - noderesourcetopologies
  verbs:
  - delete
  - list
- apiGroups:
  - nfd.k8s-sigs.io
  resources:
  - nodefeatures
  verbs:
  - delete
  - list
---
# Source: node-feature-discovery/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-feature-discovery-1711027422
  labels:
    helm.sh/chart: node-feature-discovery-0.15.3
    app.kubernetes.io/name: node-feature-discovery
    app.kubernetes.io/instance: node-feature-discovery-1711027422
    app.kubernetes.io/version: "v0.15.3"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-feature-discovery-1711027422
subjects:
- kind: ServiceAccount
  name: node-feature-discovery-1711027422
  namespace: node-feature-discovery
---
# Source: node-feature-discovery/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-feature-discovery-1711027422-gc
  labels:
    helm.sh/chart: node-feature-discovery-0.15.3
    app.kubernetes.io/name: node-feature-discovery
    app.kubernetes.io/instance: node-feature-discovery-1711027422
    app.kubernetes.io/version: "v0.15.3"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-feature-discovery-1711027422-gc
subjects:
- kind: ServiceAccount
  name: node-feature-discovery-1711027422-gc
  namespace: node-feature-discovery
---
# Source: node-feature-discovery/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: node-feature-discovery-1711027422-worker
  namespace: node-feature-discovery
  labels:
    helm.sh/chart: node-feature-discovery-0.15.3
    app.kubernetes.io/name: node-feature-discovery
    app.kubernetes.io/instance: node-feature-discovery-1711027422
    app.kubernetes.io/version: "v0.15.3"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - nfd.k8s-sigs.io
  resources:
  - nodefeatures
  verbs:
  - create
  - get
  - update
---
# Source: node-feature-discovery/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node-feature-discovery-1711027422-worker
  namespace: node-feature-discovery
  labels:
    helm.sh/chart: node-feature-discovery-0.15.3
    app.kubernetes.io/name: node-feature-discovery
    app.kubernetes.io/instance: node-feature-discovery-1711027422
    app.kubernetes.io/version: "v0.15.3"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: node-feature-discovery-1711027422-worker
subjects:
- kind: ServiceAccount
  name: node-feature-discovery-1711027422-worker
  namespace: node-feature-discovery
---
# Source: node-feature-discovery/templates/worker.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name:  node-feature-discovery-1711027422-worker
  namespace: node-feature-discovery
  labels:
    helm.sh/chart: node-feature-discovery-0.15.3
    app.kubernetes.io/name: node-feature-discovery
    app.kubernetes.io/instance: node-feature-discovery-1711027422
    app.kubernetes.io/version: "v0.15.3"
    app.kubernetes.io/managed-by: Helm
    role: worker
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: node-feature-discovery
      app.kubernetes.io/instance: node-feature-discovery-1711027422
      role: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: node-feature-discovery
        app.kubernetes.io/instance: node-feature-discovery-1711027422
        role: worker
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: node-feature-discovery-1711027422-worker
      securityContext:
        {}
      containers:
      - name: worker
        securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
        image: "registry.k8s.io/nfd/node-feature-discovery:v0.15.3"
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        resources:
            {}
        command:
        - "nfd-worker"
        args:
        - "-metrics=8081"
        ports:
          - name: metrics
            containerPort: 8081
        volumeMounts:
        - name: host-boot
          mountPath: "/host-boot"
          readOnly: true
        - name: host-os-release
          mountPath: "/host-etc/os-release"
          readOnly: true
        - name: host-sys
          mountPath: "/host-sys"
          readOnly: true
        - name: host-usr-lib
          mountPath: "/host-usr/lib"
          readOnly: true
        - name: host-lib
          mountPath: "/host-lib"
          readOnly: true
        - name: source-d
          mountPath: "/etc/kubernetes/node-feature-discovery/source.d/"
          readOnly: true
        - name: features-d
          mountPath: "/etc/kubernetes/node-feature-discovery/features.d/"
          readOnly: true
        - name: nfd-worker-conf
          mountPath: "/etc/kubernetes/node-feature-discovery"
          readOnly: true
      volumes:
        - name: host-boot
          hostPath:
            path: "/boot"
        - name: host-os-release
          hostPath:
            path: "/etc/os-release"
        - name: host-sys
          hostPath:
            path: "/sys"
        - name: host-usr-lib
          hostPath:
            path: "/usr/lib"
        - name: host-lib
          hostPath:
            path: "/lib"
        - name: source-d
          hostPath:
            path: "/etc/kubernetes/node-feature-discovery/source.d/"
        - name: features-d
          hostPath:
            path: "/etc/kubernetes/node-feature-discovery/features.d/"
        - name: nfd-worker-conf
          configMap:
            name: node-feature-discovery-1711027422-worker-conf
            items:
              - key: nfd-worker.conf
                path: nfd-worker.conf
---
# Source: node-feature-discovery/templates/master.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  node-feature-discovery-1711027422-master
  namespace: node-feature-discovery
  labels:
    helm.sh/chart: node-feature-discovery-0.15.3
    app.kubernetes.io/name: node-feature-discovery
    app.kubernetes.io/instance: node-feature-discovery-1711027422
    app.kubernetes.io/version: "v0.15.3"
    app.kubernetes.io/managed-by: Helm
    role: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: node-feature-discovery
      app.kubernetes.io/instance: node-feature-discovery-1711027422
      role: master
  template:
    metadata:
      labels:
        app.kubernetes.io/name: node-feature-discovery
        app.kubernetes.io/instance: node-feature-discovery-1711027422
        role: master
    spec:
      serviceAccountName: node-feature-discovery-1711027422
      enableServiceLinks: false
      securityContext:
        {}
      containers:
        - name: master
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          image: "registry.k8s.io/nfd/node-feature-discovery:v0.15.3"
          imagePullPolicy: IfNotPresent
          livenessProbe:
            grpc:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            grpc:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 10
          ports:
          - containerPort: 8080
            name: grpc
          - containerPort: 8081
            name: metrics
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          command:
            - "nfd-master"
          resources:
            {}
          args:
            ## By default, disable crd controller for other than the default instances
            - "-crd-controller=true"
            - "-metrics=8081"
          volumeMounts:
            - name: nfd-master-conf
              mountPath: "/etc/kubernetes/node-feature-discovery"
              readOnly: true
      volumes:
        - name: nfd-master-conf
          configMap:
            name: node-feature-discovery-1711027422-master-conf
            items:
              - key: nfd-master.conf
                path: nfd-master.conf
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: In
                values:
                - ""
            weight: 1
          - preference:
              matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: In
                values:
                - ""
            weight: 1
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Equal
          value: ""
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Equal
          value: ""
---
# Source: node-feature-discovery/templates/nfd-gc.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-feature-discovery-1711027422-gc
  namespace: node-feature-discovery
  labels:
    helm.sh/chart: node-feature-discovery-0.15.3
    app.kubernetes.io/name: node-feature-discovery
    app.kubernetes.io/instance: node-feature-discovery-1711027422
    app.kubernetes.io/version: "v0.15.3"
    app.kubernetes.io/managed-by: Helm
    role: gc
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: node-feature-discovery
      app.kubernetes.io/instance: node-feature-discovery-1711027422
      role: gc
  template:
    metadata:
      labels:
        app.kubernetes.io/name: node-feature-discovery
        app.kubernetes.io/instance: node-feature-discovery-1711027422
        role: gc
    spec:
      serviceAccountName: node-feature-discovery-1711027422-gc
      dnsPolicy: ClusterFirstWithHostNet
      securityContext:
        {}
      containers:
      - name: gc
        image: "registry.k8s.io/nfd/node-feature-discovery:v0.15.3"
        imagePullPolicy: "IfNotPresent"
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        command:
          - "nfd-gc"
        args:
          - "-gc-interval=1h"
        resources:
            {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ "ALL" ]
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        ports:
          - name: metrics
            containerPort: 8081

